config/routes.rb
Rails.application.routes.draw do

  get 'inicio/index'

  resources :pujas

  resources :historial_de_alquilers

  resources :subasta

  resources :compraventa

  resources :alquilers

  resources :cars

  resources :users

  root 'inicio#index'

end

app/models/puja.rb
class Puja < ActiveRecord::Base
	belongs_to :subastum
	belongs_to :user
	validates :id_subasta, :pujador, :valor, :fecha,  presence: true

	scope :historial_pujas, ->{where("subasta.comprador IS NULL")}

end

app/controllers/pujas_controller.rb
class PujasController < ApplicationController
  before_action :set_puja, only: [:show, :edit, :update, :destroy]

  # GET /pujas
  # GET /pujas.json
  def index
    @pujas = Puja.all
  end

  # GET /pujas/1
  # GET /pujas/1.json
  def show
  end

  # GET /pujas/new
  def new
    @puja = Puja.new
  end

  # GET /pujas/1/edit
  def edit
  end

  # POST /pujas
  # POST /pujas.json
  def create
    @puja = Puja.new(puja_params)

    respond_to do |format|
      if @puja.save
        format.html { redirect_to @puja, notice: 'Puja was successfully created.' }
        format.json { render :show, status: :created, location: @puja }
      else
        format.html { render :new }
        format.json { render json: @puja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pujas/1
  # PATCH/PUT /pujas/1.json
  def update
    respond_to do |format|
      if @puja.update(puja_params)
        format.html { redirect_to @puja, notice: 'Puja was successfully updated.' }
        format.json { render :show, status: :ok, location: @puja }
      else
        format.html { render :edit }
        format.json { render json: @puja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pujas/1
  # DELETE /pujas/1.json
  def destroy
    @puja.destroy
    respond_to do |format|
      format.html { redirect_to pujas_url, notice: 'Puja was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puja
      @puja = Puja.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puja_params
      params.require(:puja).permit(:id_subasta, :pujador, :valor, :fecha)
    end
end

app/helpers/pujas_helper.rb
module PujasHelper
end

app/views/pujas/_form.html.erb
<%= form_for(@puja) do |f| %>
  <% if @puja.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@puja.errors.count, "error") %> prohibited this puja from being saved:</h2>

      <ul>
      <% @puja.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_subasta %><br>
    <%= f.number_field :id_subasta %>
  </div>
  <div class="field">
    <%= f.label :pujador %><br>
    <%= f.number_field :pujador %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.number_field :valor %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.datetime_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pujas/edit.html.erb
<h1>Editing puja</h1>

<%= render 'form' %>

<%= link_to 'Show', @puja %> |
<%= link_to 'Back', pujas_path %>

app/views/pujas/index.html.erb
<h1>Listing pujas</h1>

<table>
  <thead>
    <tr>
      <th>Id subasta</th>
      <th>Pujador</th>
      <th>Valor</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pujas.each do |puja| %>
      <tr>
        <td><%= puja.id_subasta %></td>
        <td><%= puja.pujador %></td>
        <td><%= puja.valor %></td>
        <td><%= puja.fecha %></td>
        <td><%= link_to 'Show', puja %></td>
        <td><%= link_to 'Edit', edit_puja_path(puja) %></td>
        <td><%= link_to 'Destroy', puja, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Puja', new_puja_path %>

app/views/pujas/new.html.erb
<h1>New puja</h1>

<%= render 'form' %>

<%= link_to 'Back', pujas_path %>

app/views/pujas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id subasta:</strong>
  <%= @puja.id_subasta %>
</p>

<p>
  <strong>Pujador:</strong>
  <%= @puja.pujador %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @puja.valor %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @puja.fecha %>
</p>

<%= link_to 'Edit', edit_puja_path(@puja) %> |
<%= link_to 'Back', pujas_path %>