config/routes.rb
Rails.application.routes.draw do

  get 'inicio/index'

  resources :pujas

  resources :historial_de_alquilers

  resources :subasta

  resources :compraventa

  resources :alquilers

  resources :cars

  resources :users

  root 'inicio#index'

end

app/models/historial_de_alquiler.rb
class HistorialDeAlquiler < ActiveRecord::Base
	belongs_to :car
	#belongs_to :user
	validates :id_coche, :alquilador, :fecha_ini_alquiler, :fecha_fin_alquiler, :precio,  presence: true
end

app/controllers/historial_de_alquilers_controller.rb
class HistorialDeAlquilersController < ApplicationController
  before_action :set_historial_de_alquiler, only: [:show, :edit, :update, :destroy]

  # GET /historial_de_alquilers
  # GET /historial_de_alquilers.json
  def index
    @historial_de_alquilers = HistorialDeAlquiler.all
  end

  # GET /historial_de_alquilers/1
  # GET /historial_de_alquilers/1.json
  def show
  end

  # GET /historial_de_alquilers/new
  def new
    @historial_de_alquiler = HistorialDeAlquiler.new
  end

  # GET /historial_de_alquilers/1/edit
  def edit
  end

  # POST /historial_de_alquilers
  # POST /historial_de_alquilers.json
  def create
    @historial_de_alquiler = HistorialDeAlquiler.new(historial_de_alquiler_params)

    respond_to do |format|
      if @historial_de_alquiler.save
        format.html { redirect_to @historial_de_alquiler, notice: 'Historial de alquiler was successfully created.' }
        format.json { render :show, status: :created, location: @historial_de_alquiler }
      else
        format.html { render :new }
        format.json { render json: @historial_de_alquiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /historial_de_alquilers/1
  # PATCH/PUT /historial_de_alquilers/1.json
  def update
    respond_to do |format|
      if @historial_de_alquiler.update(historial_de_alquiler_params)
        format.html { redirect_to @historial_de_alquiler, notice: 'Historial de alquiler was successfully updated.' }
        format.json { render :show, status: :ok, location: @historial_de_alquiler }
      else
        format.html { render :edit }
        format.json { render json: @historial_de_alquiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historial_de_alquilers/1
  # DELETE /historial_de_alquilers/1.json
  def destroy
    @historial_de_alquiler.destroy
    respond_to do |format|
      format.html { redirect_to historial_de_alquilers_url, notice: 'Historial de alquiler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_historial_de_alquiler
      @historial_de_alquiler = HistorialDeAlquiler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def historial_de_alquiler_params
      params.require(:historial_de_alquiler).permit(:id_coche, :alquilador, :fecha_ini_alquiler, :fecha_fin_alquiler, :precio)
    end
end

app/helpers/historial_de_alquilers_helper.rb
module HistorialDeAlquilersHelper
end

app/views/historial_de_alquilers/_form.html.erb
<%= form_for(@historial_de_alquiler) do |f| %>
  <% if @historial_de_alquiler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@historial_de_alquiler.errors.count, "error") %> prohibited this historial_de_alquiler from being saved:</h2>

      <ul>
      <% @historial_de_alquiler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_coche %><br>
    <%= f.number_field :id_coche %>
  </div>
  <div class="field">
    <%= f.label :alquilador %><br>
    <%= f.number_field :alquilador %>
  </div>
  <div class="field">
    <%= f.label :fecha_ini_alquiler %><br>
    <%= f.datetime_select :fecha_ini_alquiler %>
  </div>
  <div class="field">
    <%= f.label :fecha_fin_alquiler %><br>
    <%= f.datetime_select :fecha_fin_alquiler %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/historial_de_alquilers/edit.html.erb
<h1>Editing historial_de_alquiler</h1>

<%= render 'form' %>

<%= link_to 'Show', @historial_de_alquiler %> |
<%= link_to 'Back', historial_de_alquilers_path %>

app/views/historial_de_alquilers/index.html.erb
<h1>Listing historial_de_alquilers</h1>

<table>
  <thead>
    <tr>
      <th>Id coche</th>
      <th>Alquilador</th>
      <th>Fecha ini alquiler</th>
      <th>Fecha fin alquiler</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @historial_de_alquilers.each do |historial_de_alquiler| %>
      <tr>
        <td><%= historial_de_alquiler.id_coche %></td>
        <td><%= historial_de_alquiler.alquilador %></td>
        <td><%= historial_de_alquiler.fecha_ini_alquiler %></td>
        <td><%= historial_de_alquiler.fecha_fin_alquiler %></td>
        <td><%= historial_de_alquiler.precio %></td>
        <td><%= link_to 'Show', historial_de_alquiler %></td>
        <td><%= link_to 'Edit', edit_historial_de_alquiler_path(historial_de_alquiler) %></td>
        <td><%= link_to 'Destroy', historial_de_alquiler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Historial de alquiler', new_historial_de_alquiler_path %>

app/views/historial_de_alquilers/new.html.erb
<h1>New historial_de_alquiler</h1>

<%= render 'form' %>

<%= link_to 'Back', historial_de_alquilers_path %>

app/views/historial_de_alquilers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id coche:</strong>
  <%= @historial_de_alquiler.id_coche %>
</p>

<p>
  <strong>Alquilador:</strong>
  <%= @historial_de_alquiler.alquilador %>
</p>

<p>
  <strong>Fecha ini alquiler:</strong>
  <%= @historial_de_alquiler.fecha_ini_alquiler %>
</p>

<p>
  <strong>Fecha fin alquiler:</strong>
  <%= @historial_de_alquiler.fecha_fin_alquiler %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @historial_de_alquiler.precio %>
</p>

<%= link_to 'Edit', edit_historial_de_alquiler_path(@historial_de_alquiler) %> |
<%= link_to 'Back', historial_de_alquilers_path %>