config/routes.rb
Rails.application.routes.draw do

  get 'inicio/index'

  resources :pujas

  resources :historial_de_alquilers

  resources :subasta

  resources :compraventa

  resources :alquilers

  resources :cars

  resources :users

  root 'inicio#index'

end

app/models/alquiler.rb
class Alquiler < ActiveRecord::Base
	belongs_to :car
	belongs_to :user
	validates :id_coche, :fecha_ini_anuncio, :fecha_fin_anuncio, :fecha_ini_alquiler, :fecha_fin_alquiler, :precio,  presence: true

	scope :alquileres_disponible, ->{where("alquilers.alquilador IS NULL")}
end

app/controllers/alquilers_controller.rb
class AlquilersController < ApplicationController
  before_action :set_alquiler, only: [:show, :edit, :update, :destroy]

  # GET /alquilers
  # GET /alquilers.json
  def index
    @alquilers = Alquiler.all
  end

  # GET /alquilers/1
  # GET /alquilers/1.json
  def show
  end

  # GET /alquilers/new
  def new
    @alquiler = Alquiler.new
  end

  # GET /alquilers/1/edit
  def edit
  end

  # POST /alquilers
  # POST /alquilers.json
  def create
    @alquiler = Alquiler.new(alquiler_params)

    respond_to do |format|
      if @alquiler.save
        format.html { redirect_to @alquiler, notice: 'Alquiler was successfully created.' }
        format.json { render :show, status: :created, location: @alquiler }
      else
        format.html { render :new }
        format.json { render json: @alquiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alquilers/1
  # PATCH/PUT /alquilers/1.json
  def update
    respond_to do |format|
      if @alquiler.update(alquiler_params)
        format.html { redirect_to @alquiler, notice: 'Alquiler was successfully updated.' }
        format.json { render :show, status: :ok, location: @alquiler }
      else
        format.html { render :edit }
        format.json { render json: @alquiler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alquilers/1
  # DELETE /alquilers/1.json
  def destroy
    @alquiler.destroy
    respond_to do |format|
      format.html { redirect_to alquilers_url, notice: 'Alquiler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alquiler
      @alquiler = Alquiler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alquiler_params
      params.require(:alquiler).permit(:id_coche, :alquilador, :fecha_ini_anuncio, :fecha_fin_anuncio, :fecha_ini_alquiler, :fecha_fin_alquiler, :precio)
    end
end

app/helpers/alquilers_helper.rb
module AlquilersHelper
end

app/views/alquilers/_form.html.erb
<%= form_for(@alquiler) do |f| %>
  <% if @alquiler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alquiler.errors.count, "error") %> prohibited this alquiler from being saved:</h2>

      <ul>
      <% @alquiler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_coche %><br>
    <%= f.number_field :id_coche %>
  </div>
  <div class="field">
    <%= f.label :alquilador %><br>
    <%= f.number_field :alquilador %>
  </div>
  <div class="field">
    <%= f.label :fecha_ini_anuncio %><br>
    <%= f.datetime_select :fecha_ini_anuncio %>
  </div>
  <div class="field">
    <%= f.label :fecha_fin_anuncio %><br>
    <%= f.datetime_select :fecha_fin_anuncio %>
  </div>
  <div class="field">
    <%= f.label :fecha_ini_alquiler %><br>
    <%= f.datetime_select :fecha_ini_alquiler %>
  </div>
  <div class="field">
    <%= f.label :fecha_fin_alquiler %><br>
    <%= f.datetime_select :fecha_fin_alquiler %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.number_field :precio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alquilers/edit.html.erb
<h1>Editing alquiler</h1>

<%= render 'form' %>

<%= link_to 'Show', @alquiler %> |
<%= link_to 'Back', alquilers_path %>

app/views/alquilers/index.html.erb
<h1>Listing alquilers</h1>

<table>
  <thead>
    <tr>
      <th>Id coche</th>
      <th>Alquilador</th>
      <th>Fecha ini anuncio</th>
      <th>Fecha fin anuncio</th>
      <th>Fecha ini alquiler</th>
      <th>Fecha fin alquiler</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alquilers.each do |alquiler| %>
      <tr>
        <td><%= alquiler.id_coche %></td>
        <td><%= alquiler.alquilador %></td>
        <td><%= alquiler.fecha_ini_anuncio %></td>
        <td><%= alquiler.fecha_fin_anuncio %></td>
        <td><%= alquiler.fecha_ini_alquiler %></td>
        <td><%= alquiler.fecha_fin_alquiler %></td>
        <td><%= alquiler.precio %></td>
        <td><%= link_to 'Show', alquiler %></td>
        <td><%= link_to 'Edit', edit_alquiler_path(alquiler) %></td>
        <td><%= link_to 'Destroy', alquiler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alquiler', new_alquiler_path %>

app/views/alquilers/new.html.erb
<h1>New alquiler</h1>

<%= render 'form' %>

<%= link_to 'Back', alquilers_path %>

app/views/alquilers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id coche:</strong>
  <%= @alquiler.id_coche %>
</p>

<p>
  <strong>Alquilador:</strong>
  <%= @alquiler.alquilador %>
</p>

<p>
  <strong>Fecha ini anuncio:</strong>
  <%= @alquiler.fecha_ini_anuncio %>
</p>

<p>
  <strong>Fecha fin anuncio:</strong>
  <%= @alquiler.fecha_fin_anuncio %>
</p>

<p>
  <strong>Fecha ini alquiler:</strong>
  <%= @alquiler.fecha_ini_alquiler %>
</p>

<p>
  <strong>Fecha fin alquiler:</strong>
  <%= @alquiler.fecha_fin_alquiler %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @alquiler.precio %>
</p>

<%= link_to 'Edit', edit_alquiler_path(@alquiler) %> |
<%= link_to 'Back', alquilers_path %>